ALTER TABLE `categories` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `categories` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories` MODIFY COLUMN `collection_id` int(11) NOT NULL;
ALTER TABLE `categories` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `categories` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `categories` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `categories` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `categories` MODIFY COLUMN `description` text;
ALTER TABLE `categories` MODIFY COLUMN `elements_count` int(11) NOT NULL DEFAULT '0';

ALTER TABLE `categories_properties` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `categories_properties` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories_properties` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories_properties` MODIFY COLUMN `category_id` int(11) NOT NULL;
ALTER TABLE `categories_properties` MODIFY COLUMN `property_id` int(11) NOT NULL;
ALTER TABLE `categories_properties` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories_properties` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories_properties` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `categories_properties` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories_properties` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `categories_properties` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `categories_properties` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `collections` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `collections` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `name` varchar(45) NOT NULL;
ALTER TABLE `collections` MODIFY COLUMN `description` text;
ALTER TABLE `collections` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `collections` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `collections` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `collections` MODIFY COLUMN `elements_count` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `categories_count` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `properties_count` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `elementorders_count` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `collections` MODIFY COLUMN `products_count` int(11) NOT NULL DEFAULT '0';

ALTER TABLE `comments` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `comments` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `comments` MODIFY COLUMN `parent_id` int(11) NOT NULL;
ALTER TABLE `comments` MODIFY COLUMN `comment` text NOT NULL;
ALTER TABLE `comments` MODIFY COLUMN `foreign_id` int(11) NOT NULL;
ALTER TABLE `comments` MODIFY COLUMN `collection_id` int(11) NOT NULL;
ALTER TABLE `comments` MODIFY COLUMN `model` int(11) NOT NULL;
ALTER TABLE `comments` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `comments` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `comments` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `comments` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `comments` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `comments` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `comments` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `elementorders` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `elementorders` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `status` int(11) DEFAULT '1';
ALTER TABLE `elementorders` MODIFY COLUMN `name` varchar(45) DEFAULT NULL;
ALTER TABLE `elementorders` MODIFY COLUMN `datecreated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders` MODIFY COLUMN `dateordered` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders` MODIFY COLUMN `collection_id` int(11) NOT NULL;
ALTER TABLE `elementorders` MODIFY COLUMN `synced` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `quantity_type` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders` MODIFY COLUMN `orderelements_count` int(11) NOT NULL DEFAULT '0';

ALTER TABLE `elementorders_properties` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `elementorders_properties` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `elementorder_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `property_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders_properties` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elementorders_properties` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elementorders_properties` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `elements` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `elements` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `category_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `name` varchar(45) NOT NULL;
ALTER TABLE `elements` MODIFY COLUMN `description` varchar(200) DEFAULT NULL;
ALTER TABLE `elements` MODIFY COLUMN `quantity` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `warning_quantity` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements` MODIFY COLUMN `copy_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements` MODIFY COLUMN `revision_reason` varchar(255) NOT NULL;

ALTER TABLE `elements_products` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `elements_products` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `product_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `element_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `element_count` int(11) NOT NULL DEFAULT '9';
ALTER TABLE `elements_products` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements_products` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements_products` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_products` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `elements_properties` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `elements_properties` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `element_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `property_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `property_value` varchar(255) DEFAULT NULL;
ALTER TABLE `elements_properties` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements_properties` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `elements_properties` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `elements_properties` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `events` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `events` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `events` MODIFY COLUMN `type` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `events` MODIFY COLUMN `model` varchar(32) NOT NULL;
ALTER TABLE `events` MODIFY COLUMN `foreign_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `events` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `events` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `events` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `events` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `events` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `events` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `files` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `files` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `files` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `files` MODIFY COLUMN `mime` varchar(32) NOT NULL;
ALTER TABLE `files` MODIFY COLUMN `size` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `files` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `files` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `files` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `files` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `files` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `files` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `files` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `files` MODIFY COLUMN `servername` varchar(48) NOT NULL;
ALTER TABLE `files` MODIFY COLUMN `md5hash` varchar(32) NOT NULL;

ALTER TABLE `orderelements` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `orderelements` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `number` varchar(20) NOT NULL;
ALTER TABLE `orderelements` MODIFY COLUMN `desiredquantity` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `minquantity` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `ordered` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `purpose` varchar(100) DEFAULT NULL;
ALTER TABLE `orderelements` MODIFY COLUMN `description` varchar(200) DEFAULT NULL;
ALTER TABLE `orderelements` MODIFY COLUMN `elementorder_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `element_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `collection_id` int(11) NOT NULL;
ALTER TABLE `orderelements` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `orderelements` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `orderelements` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `orderelements` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `products` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `products` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products` MODIFY COLUMN `collection_id` int(11) NOT NULL;
ALTER TABLE `products` MODIFY COLUMN `name` varchar(45) DEFAULT NULL;
ALTER TABLE `products` MODIFY COLUMN `description` text;
ALTER TABLE `products` MODIFY COLUMN `quantity` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `products` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `products` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `products_subproducts` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `products_subproducts` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `product_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `subproduct_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `subproduct_count` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `products_subproducts` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `products_subproducts` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `products_subproducts` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `properties` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `properties` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `name` varchar(255) NOT NULL;
ALTER TABLE `properties` MODIFY COLUMN `description` text NOT NULL;
ALTER TABLE `properties` MODIFY COLUMN `data_type` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `unit` varchar(45) DEFAULT NULL;
ALTER TABLE `properties` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `properties` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `properties` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `properties` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `properties` MODIFY COLUMN `propertychoices_count` int(11) NOT NULL DEFAULT '0';

ALTER TABLE `propertychoices` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `propertychoices` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `property_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `choice` varchar(45) DEFAULT NULL;
ALTER TABLE `propertychoices` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `propertychoices` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `propertychoices` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `propertychoices` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `tokens` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `tokens` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `tokens` MODIFY COLUMN `type` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `tokens` MODIFY COLUMN `user_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `tokens` MODIFY COLUMN `code` varchar(64) NOT NULL;
ALTER TABLE `tokens` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `tokens` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `tokens` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `tokens` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `tokens` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `tokens` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `users` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `username` varchar(45) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `password` varchar(64) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `access_group` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `first_name` varchar(45) DEFAULT NULL;
ALTER TABLE `users` MODIFY COLUMN `last_name` varchar(45) DEFAULT NULL;
ALTER TABLE `users` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` MODIFY COLUMN `last_login` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` MODIFY COLUMN `lock_code` varchar(10) NOT NULL DEFAULT '1234';
ALTER TABLE `users` MODIFY COLUMN `dynamic_token` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users` MODIFY COLUMN `image` varchar(70) DEFAULT NULL;

ALTER TABLE `usersettings` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `usersettings` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usersettings` MODIFY COLUMN `user_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usersettings` MODIFY COLUMN `setting` varchar(32) NOT NULL;
ALTER TABLE `usersettings` MODIFY COLUMN `value` varchar(32) NOT NULL;
ALTER TABLE `usersettings` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usersettings` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `usersettings` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usersettings` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `usersettings` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usersettings` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `users_collections` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `users_collections` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `user_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `collection_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users_collections` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users_collections` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `users_collections` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `usertokens` MODIFY COLUMN `id` int(11) NOT NULL;
ALTER TABLE `usertokens` MODIFY COLUMN `revision_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usertokens` MODIFY COLUMN `token` varchar(64) DEFAULT NULL;
ALTER TABLE `usertokens` MODIFY COLUMN `dynamic_token` varchar(64) NOT NULL;
ALTER TABLE `usertokens` MODIFY COLUMN `validto` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `usertokens` MODIFY COLUMN `created_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usertokens` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `usertokens` MODIFY COLUMN `modified_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usertokens` MODIFY COLUMN `modified_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `usertokens` MODIFY COLUMN `deleted_by` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usertokens` MODIFY COLUMN `deleted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `usertokens` MODIFY COLUMN `user_id` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usertokens` MODIFY COLUMN `ip` varchar(20) DEFAULT NULL;
ALTER TABLE `usertokens` MODIFY COLUMN `deleted` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `usertokens` MODIFY COLUMN `next_token` varchar(48) DEFAULT NULL;
ALTER TABLE `usertokens` MODIFY COLUMN `invalidated` int(11) NOT NULL DEFAULT '0';